### ISSUE TITLE
Missing Rarity Data?

### ISSUE THREAD

**Issue by emorling** [OpenRarity/open-rarity#63] opened 2022-09-25 13:21 UTC
> Here is promised update with the OpenSea API that provides rarity data right now on the [Assets API endpoint](https://docs.opensea.io/reference/asset-object#rarity-data) . We are still figuring out how to support other languages than python, but this should give you a straight integration point for TS.

Should we expect collections to have rarity data? I made a quick test with a BAYC item here:

`https://opensea.io/assets/ethereum/0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d/5118`

However, the rarity data is null? Should this be expected?

**Comment by emorling** [comment] 2022-09-25 13:28
I tried several other prominent collections, and all seem to be missing Rarity data.

**Comment by impreso** [comment] 2022-09-26 19:29
Hi @emorling this is probably because they are not opt-in yet. We only show rarity data for Opt-in collections.

**Comment by emorling** [comment] 2022-09-26 20:51
> Hi @emorling this is probably because they are not opt-in yet. We only show rarity data for Opt-in collections.

I see... so there is no standardized fallback?

**Comment by impreso** [comment] 2022-09-26 21:02
Realistically just by running the library on your compute.

**Comment by emorling** [comment] 2022-09-26 21:03
I was hoping we would have a rarity for all collections on OpenSea 😁

**Comment by impreso** [comment] 2022-09-27 17:13
Yes, we are working on the coverage improvement.

**Comment by impreso** [comment] 2022-09-27 17:13
Should we close it , since it's not a bug but rather works as intended :)

**Closed** 2022-09-27 17:15 UTC
Labels: bug

**Comment by chrysb** [comment] 2022-09-27 19:52
@emorling You can check the collection endpoint of the OpenSea API and see if `is_rarity_enabled` is true
