### ISSUE TITLE
Using OpenSea Helpers with Mutant Ape Yacht Club

### ISSUE THREAD

**Issue by kunalsnaik** [OpenRarity/open-rarity#81] opened 2022-10-10 22:01 UTC
**Describe the bug**
Hi, this library has been very helpful for me so far. I am currently trying to use the get_collection_from_opensea function with the slug for Mutant Ape Yacht Club (mutant-ape-yacht-club). For some reason, I am only getting ~14,500 tokens back when there are closer to ~19,500 total tokens. collection.token_total_supply is at ~14,500.

Does anyone know why this is the case? Thanks very much!

**Information**

* Collection link/name: https://opensea.io/collection/mutant-ape-yacht-club
* Contract standard
* Chain

**To Reproduce**
collection = get_collection_from_opensea('mutant-ape-yach-club')
print(collection.token_total_supply)

**Expected behavior**
Retrieve ~19,500 tokens

**Screenshots**

**Environment**
 - Python [e.g. 3.10.3]
 - Library Version [e.g. 1.0]

**Additional context**

**Comment by vickygos** [comment] 2022-10-12 23:13
Hello, thank you for the report.
We believe it is a duplicate of this issue. https://github.com/OpenRarity/open-rarity/issues/68#issue-1390040945 as we currently do not properly support it when token ids are not sequential. We have this on our backlog but a temporary solution is mentioned in thread

**Comment by kunalsnaik** [comment] 2022-10-13 20:22
Got it, appreciate the reponse

**Comment by impreso** [comment] 2023-02-07 03:21
Resolving as duplciate

**Closed by impreso** 2023-02-07 03:21 UTC
Labels: bug
